# Generated by Django 5.2.5 on 2025-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dressType',
            field=models.CharField(choices=[('C', 'Casual'), ('F', 'Formal'), ('P', 'Party'), ('G', 'Gym')], default=('C', 'Casual'), max_length=20),
        ),
    ]
