# Generated by Django 5.2.5 on 2025-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttranslation',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
