# Generated by Django 5.2.5 on 2025-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_product_name_producttranslation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='SKU', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=10),
        ),
    ]
