# Generated by Django 5.2.5 on 2025-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_sku_product_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='carted_size',
            field=models.CharField(default='M', max_length=10),
        ),
    ]
