# Generated by Django 5.2.5 on 2025-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cart_carted_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_stock',
            field=models.IntegerField(default=10),
        ),
    ]
