# Generated by Django 5.2.5 on 2025-10-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cart_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_stock',
        ),
    ]
