# Generated by Django 5.2.5 on 2025-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_cart_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
