# Generated by Django 5.2.5 on 2025-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selled_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
