# Generated by Django 5.2.5 on 2025-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cart_selled_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='selled_counts',
        ),
        migrations.AddField(
            model_name='product',
            name='selled_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
